sonata_notification:
    class:
        message: App\Application\Sonata\NotificationBundle\Entity\Message
    backend: sonata.notification.backend.runtime
    consumers:
        register_default: false
    admin:
        enabled: false
